### ISSUE TITLE
4.4.0之前破解，完美运行了~ 这两天突然自动升级到4.4.1，大姨妈了。尝试再次安装4.4.0，在破解，失败~

### ISSUE THREAD

**Issue by Doutianbao** [JuncoJet/unlimited-landeng-for-win#12]
如题
有一样问题的人吗？
@JuncoJet 大神

**Comment by gokokusan** [comment]
nice

**Comment by molixiaoge** [comment]
不是有禁止更新方法么

**Comment by zfk513** [comment]
补丁能打上，但是蓝灯开一会就崩……

**Comment by Doutianbao** [comment]
同上~

**Comment by JuncoJet** [comment]
https://github.com/JuncoJet/unlimited-landeng-for-win/issues/2#issuecomment-333881084

**Comment by zfk513** [comment]
可是我们用的就是4.4.0的版本啊

**Comment by wddfzfx** [comment]
不要再用垃圾lantern了， 买了年费就不管了，肠子都悔青了!
推荐一个自用的shadowsocks SS/SSR服务商，一直在用，速度杠杠的~|价|格|优|惠|低至5元/50G/月。在最近跑路关停潮日益严重的日子,依旧坚挺~已屏蔽国内ip，需翻墙访问～
http://cp.dawangidc.com/aff.php?aff=523
购买服务后请看配置教程
https://fqjsjl.tumblr.com
