### ISSUE TITLE
lantern自动升级后的最新版本此补丁无效，打上后程序崩溃无法启动

### ISSUE THREAD

**Issue by zhezhe168** [JuncoJet/unlimited-landeng-for-win#2]
lantern自动升级后的最新版本此补丁无效，打上后程序崩溃无法启动

**Comment by JuncoJet** [comment]
用老版本 然后记事本新建一个 `.lantern.exe.new` 空文件，设置成只读，可防止升级

**Comment by drliu1202** [comment]
https://github.com/getlantern/lantern/tags
旧版下载网页
https://github.com/getlantern/lantern/releases/download/4.2.5/update_windows_386.bz2

**Comment by zxp209** [comment]
怎么用哦

**Comment by zxp209** [comment]
我打开蓝灯之后就是一个网页，补丁怎么打上去啊
