### ISSUE TITLE
蓝灯版本一直是4.4.0，没有自动升级，但是闪退，打开蓝灯秒退或者过几秒自动退出

### ISSUE THREAD

**Issue by ieatczp** [JuncoJet/unlimited-landeng-for-win#25]
根据大家的奇思妙招，没让蓝灯升级，一直是4.4.0，每次打开蓝灯的时候，左下角版本号都是4.4.0。但是现在有个问题，那就是闪退，打开客户端就自动退出。仔细回想一下，所有步骤都是按照JuncoJet大神说的那样来的，lantern.dll也导入了。请问大家还有什么招儿？
曾经尝试过，把lantern.dll移除后登录就不会闪退。
是不是lantern现在每次启动的时候都会检查新版本？如果版本不是最新且无法更新的情况下就玩儿闪退？大神们怎么看？有什么好的解决办法？谢谢~

**Comment by JuncoJet** [comment]
WIN10关DEP，找前面的帖子
