### ISSUE TITLE
最看不起你这种作者了

### ISSUE THREAD

**Issue by iamqk** [JuncoJet/unlimited-landeng-for-win#27]
破解别人的程序，你让别人怎么继续发展啊？
还搞到开源社区
真是恶心

**Comment by rgj226** [comment]
支持作者！

**Comment by JuncoJet** [comment]
楼主说的好像很伟大啊 没用过windows没用过office？自己天天在用破解软件却指责别人不能破解

**Comment by JuncoJet** [comment]
最看不起你这种楼主了
真是恶心

**Comment by iamqk** [comment]
用过我也是偷偷摸摸的用，从来没有传播和扩散，而且能负担的软件我都会用正版的
不像某些人，明明知道是违法的、盗版的，还大张旗鼓的使用，而且放到开源社区，共享给他人
开源社区就是你这种精神的人组成的么？
@JuncoJet

**Comment by JuncoJet** [comment]
首先这个开源的东西并非剽窃，其次这个开源的东西并没有封装别人的库有也只是C库，代码完全作者自己一行一行写出来的。这里面哪里违法，是不是linus写了个内核，和unix操作一样提供的接口一样就是盗版，你是来搞笑的么？
@iamqk

**Comment by iamqk** [comment]
你不要在这里为自己洗地了，vpn不需要租借服务器？人家代码开源，资源也开源？你才是搞笑的
你的lantern不是走人家的服务器的流量？
太搞笑了，见过不要脸的，没见想你这样的
@JuncoJet

**Comment by JuncoJet** [comment]
我的lantern连socket都没包含，哪来的流量之说，你是不是根本就没看过代码，如果没看过那你也不用看了就当你乱叫 @iamqk

**Comment by iamqk** [comment]
呵呵，这种还用看么？
我才不信你这种人会自己架服务器给大家免费用
你这种程序员也就搞点偷鸡摸狗的事情吧
其他真的不行
