### ISSUE TITLE
老是崩溃，不知道为啥

### ISSUE THREAD

**Issue by gokokusan** [JuncoJet/unlimited-landeng-for-win#4]
来回改来好几次，改完后打开蓝灯，进去蓝灯界面，无法链接，改回来后还能用（已经被限速）。（不知道是不是我的蓝灯流量已经用完，被限制的原因）

**Comment by JuncoJet** [comment]
注意对应版本，版本对应该能正常用，还有最近灯不稳

**Comment by gokokusan** [comment]
已经可以了  😭   莫名奇妙  我明明 用lordpe  改回来了啊。

**Comment by gokokusan** [comment]
总之谢谢  我给你们点一颗星星

**Comment by gokokusan** [comment]
![image](https://user-images.githubusercontent.com/32605008/32529555-2cc4293c-c474-11e7-8d35-c7850fc6c686.png)
