### ISSUE TITLE
补丁打上来了，但是没法用呢~

### ISSUE THREAD

**Issue by Doutianbao** [JuncoJet/unlimited-landeng-for-win#9]
![tim 20171130155621](https://user-images.githubusercontent.com/25342342/33419792-0cfa1fa6-d5e7-11e7-9315-43ae61c03a1b.png)
如何才能稳~

**Comment by Doutianbao** [comment]
@JuncoJet

**Comment by JuncoJet** [comment]
你先测试本身稳不稳

**Comment by Doutianbao** [comment]
@JuncoJet   你一直能用高速流量吗？   我就用了一会儿，使用量绝对哦超过500m份额，
今，突然大姨妈，然后能用，单速度感人

**Comment by Doutianbao** [comment]
我日~，在我发上条信息的后一秒，清零了，继续高速网络，神奇！  Thanks♪(･ω･)ﾉ大神的作品，奢求更稳~~~~

**Comment by JuncoJet** [comment]
把配置文件里480改小一点
